### ISSUE TITLE
新手！使用过程中的疑问

### ISSUE THREAD

**Issue by JakeGi** [xiongcaichang/CCNavTab#6]
现在项目中有个需求， 如果没有登录的情况下，点击个人中心，push登录页面，如果登录，加载个人中心，个人中心是tabbar上的一个item， 我现在怎么获取点击的这个item，然后实现这个功能 啊

**Comment by xiongcaichang** [comment]
完全不需要，你在  个人中心的ViewWillAppear中判断加载不同的视图就可以了。

**Comment by JakeGi** [comment]
谢谢啊，我试了这样也是可以的，但是有个问题，就是如果我判断后，push过去的页面，返回后，有会自动push过去，我猜想是不是因为，我在viewWillAppear中判断的，而返回后那个item还是被选中的，所以加载视图的时候有去判断了，然后就自动push过去了

**Comment by xiongcaichang** [comment]
判断条件应该是登录状态，登录状态为true  则不跳转
